build-and-push-docker-image:
  needs: test-backend
  runs-on: ubuntu-22.04
  steps:
    - name: Checkout code
      uses: actions/checkout@v2.5.0

    - name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
        context: ./simple-api
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/devops-livecoding:latest
        push: ${{ github.ref == 'refs/heads/main' }}
